[package]
name = "reflex-wasm"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Marshall Wace LLP <opensource@mwam.com>", "Tim Kendrick <t.kendrick@mwam.com>", "Jordan Hall <j.hall@mwam.com>", "Chris Campbell <c.campbell@mwam.com>"]
edition = "2021"

[dependencies]
reflex = { path = "../reflex" }
reflex-macros = { path = "../reflex-macros" }
reflex-utils = { path = "../reflex-utils" }
chrono = "0.4"
serde_json = "1.0"
strum = "0.22"
strum_macros = "0.22"
swc_common = "0.29.16"
swc_ecma_ast = "0.94.21"
swc_ecma_parser = "0.122.31"
